---

- name: kubeconfig
  lineinfile:
    path: ~/.bash_profile
    line: "{{ kubeconfig }}"
    state: present

- name: ocp login
  command: "oc login --insecure-skip-tls-verify=true -u {{ admin_user }} -p {{ admin_user_password }}"