---

- name: binary classification demo deployment
  hosts: bastion
  vars_files:
    - "group_vars/general.yaml"
    - "group_vars/project.yaml"
  gather_facts: false
  roles:
    - general
    - authentication
